// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLmbwVuFn6cU5I7qZkViyOuiAKLNRCAg',
    appId: '1:229866312091:web:bdd757697ec3dff305d13e',
    messagingSenderId: '229866312091',
    projectId: 'new--signin-b3260',
    authDomain: 'new--signin-b3260.firebaseapp.com',
    storageBucket: 'new--signin-b3260.appspot.com',
    measurementId: 'G-7KJNBJZJ86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFEOUYXljUXj5Dpo1Ov0KUSOeTLFfO_0',
    appId: '1:229866312091:android:b6b707dcda71cb4b05d13e',
    messagingSenderId: '229866312091',
    projectId: 'new--signin-b3260',
    storageBucket: 'new--signin-b3260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBztm6ycK8vcaNECJaO5pMnohJeh6csDFY',
    appId: '1:229866312091:ios:0934312d6507604d05d13e',
    messagingSenderId: '229866312091',
    projectId: 'new--signin-b3260',
    storageBucket: 'new--signin-b3260.appspot.com',
    iosBundleId: 'com.example.newGoogleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBztm6ycK8vcaNECJaO5pMnohJeh6csDFY',
    appId: '1:229866312091:ios:bbf1387cf4b94ae705d13e',
    messagingSenderId: '229866312091',
    projectId: 'new--signin-b3260',
    storageBucket: 'new--signin-b3260.appspot.com',
    iosBundleId: 'com.example.newGoogleSignin.RunnerTests',
  );
}
